version: "3.9"

services:
  monitor:
    build: aleatorio
    container_name: script_aleatorio
    logging:
      #driver: "json.file"
      options:
        max-file: "5"
        max-size: "200m"
    volumes:
      - data-volume:/workdir

  web:
    image: nginx
    container_name: webserver
    restart: unless-stopped         
    volumes:
      - data-volume:/workdir
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"    
    command: sh -c "ln -s /workdir /usr/share/nginx/html/ && /etc/init.d/nginx start && tail -f /etc/nginx/nginx.conf"

volumes:
  data-volume:
  
  
      
